DOC-4125
couchbase/docs-sdk-dotnet pull request #1
Opened 2018-09-25 12:09 UTC by RichardSmedley

Release Notes - plus Project Docs section

2018-09-28 06:12 UTC, ingenthr requested changes

2018-09-28 06:12 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +in https://www.nuget.org/packages/CouchbaseNetClient/[NuGet]{.xref}.
In the future, this may change…

2018-09-28 06:12 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +general. NuGet is a centralized repository for package authors and
We can probably cut this second sentence, as NuGet is more well understood now.

2018-09-28 06:12 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the IDE, right-click the project you want to add the dependency
Is this the right way to do bullets @RichardSmedley ?

2018-09-28 06:12 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the Visual Studio menu bar, click *Tools*.
Is this correct adoc formatting @RichardSmedley ?  Since these are menu things, maybe they should be in fixed width or such?

As a reviewer, is there a doc I can refer to on formatting standards @amarantha-k or @RichardSmedley ?

2018-09-28 15:22 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +in https://www.nuget.org/packages/CouchbaseNetClient/[NuGet]{.xref}.
we package --> we currently package

2018-09-28 15:22 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +general. NuGet is a centralized repository for package authors and
Okay

2018-09-28 15:54 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the IDE, right-click the project you want to add the dependency
For ordered lists in AsciiDoctor, the dot is syntactic sugar for 1., 2., 3., ...

2018-09-28 15:54 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the IDE, right-click the project you want to add the dependency
https://asciidoctor.org/docs/asciidoc-writers-guide/#ordering-the-things

2018-09-28 15:54 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the Visual Studio menu bar, click *Tools*.
We seem to be using *bold* fairly consistently 
Note that, unlike Markdown, * is always bold, not italic - https://asciidoctor.org/docs/asciidoc-writers-guide/#mild-punctuation-strong-impact

Standards I've been using:
https://asciidoctor.org/docs/asciidoc-writers-guide/
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
... although Antora is destined to overload or even depart exact use of AsciiDoc / AsciiDoctor, I believe.

2018-09-28 15:54 UTC, RichardSmedley commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the Visual Studio menu bar, click *Tools*.
GitHub changed * bold * to *bold* (sigh)

2018-10-02 04:40 UTC, ingenthr approved these changes

2018-10-02 04:40 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +. From the Visual Studio menu bar, click *Tools*.
Sounds good.  I might appeal for some kind of Couchbase style guide onepager for folks like me that dip in every once in a while.

2018-10-02 04:40 UTC, ingenthr commented on modules/ROOT/pages/sdk-licenses.adoc
> +A complete list of licenses for all Couchbase components and third-party dependencies can be found https://www.couchbase.com/legal/agreements[here].
I sent a note to Chin.  This page doesn't actually list the third-party dependencies (either the described ones or the ones we ship bundled in one form or another).  We've certainly supplied this at various points over the years.

2018-10-02 14:39 UTC, RichardSmedley reviewed
Thanks for all of the input.
When the releases have been made this week, let's come back and keep improving these pages. :+1:

2018-10-02 14:39 UTC, RichardSmedley commented on modules/ROOT/pages/sdk-licenses.adoc
> +A complete list of licenses for all Couchbase components and third-party dependencies can be found https://www.couchbase.com/legal/agreements[here].
Noted - the ongoing ticket on the licensing needs some more input - this page is a sort of MVP to have something there, and an indication (I hope) that we're intending to do more. :)

2018-10-02 14:40 UTC, merged