DEVADV-192 n1ql queries with sdk page validation/update
couchbase/docs-sdk-dotnet pull request #111
Opened 2020-06-05 13:10 UTC by mgroves

I've read through this document and made some improvements/fixes. Most notably, some of the code samples were incorrect.

I've also checked in the full .net project that this page is pulling code samples from. In the future, when it's possible to point to a complete code sample, this page should be updated.

2020-06-05 19:07 UTC, AV25242 requested changes
I carefully went through the changes as someone without prior CB experience, overall very nice effort. I have few comments that will help immensely and will make it consistent with Java docs.

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
the primary index should **be** not be used.... please remove the extra **be**

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
> +== Parameterization
Queries & Placeholders is currently being used across all SDK except Java, I agree that this needs to be changed. Can you make it consistent  and call this section **Paramerterized Queries**

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
> +There are two variants of parameters: positional and named.
good point on SQL Injection, will help to provide a [link](https://owasp.org/www-community/attacks/SQL_Injection)

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/examples/n1ql-queries-sdk/n1ql-queries-sdk/Program.cs
> +                var name = row.name;        // "Mike"
should this not be Mike AtPlus ?

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/examples/n1ql-queries-sdk/n1ql-queries-sdk/Program.cs
> +                var name = row.name;        // "Mike"
Should the output not be mike RequestPlus as this is remarks consistency ?

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
>  Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.
Great examples, however reading it as a new developer have the following questions 
a) Are we starting of with an assumption that a document with user name "Mike" already exist ?
b) I see that the code examples has comments but can that be written against each consistency level.

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/examples/n1ql-queries-sdk/n1ql-queries-sdk/Program.cs
> +                var name = row.name;        // "Mike"
Is Mike in a document that already exist ? If thats the case can we have a mention of this somewhere ?

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
We should add a section that tells us the different QueryOptions that are available today, just like the Java document does
https://docs.couchbase.com/java-sdk/3.0/howtos/n1ql-queries-with-sdk.html

2020-06-05 19:07 UTC, AV25242 commented on modules/howtos/examples/n1ql-queries-sdk/n1ql-queries-sdk/Program.cs
> +            if (result.MetaData.Status != QueryStatus.Success)
Can we also add a section about what to expect out of a query result ?  There is a Handling results section that can probably changed to Query Results with different options available to us !

2020-06-05 19:11 UTC, jeffrymorris commented
@mgroves  - I also have an examples project locally with examples for "Connection Management" page which I am _still working on_ (yes @RichardSmedley its coming!). Once this is merged I will pull it and locally merge my stuff into this project.

Thanks,

Jeff

2020-06-05 19:15 UTC, mgroves commented
Thanks for the suggestions @av25242 I will work on these next week

2020-06-08 18:23 UTC, mgroves commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
> +== Parameterization
"Parameterized" but yes that's good :)

2020-06-08 18:28 UTC, mgroves commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
>  Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.
a) Are we starting of with an assumption that a document with user name "Mike" already exist ?

The code sample use upsert, so it doesn't assume that. The only time this really matter is for the NotBounded, where running it the first time would (probably) not return a result.

b) I see that the code examples has comments but can that be written against each consistency level.

What kind of comment would you like to see?

2020-06-08 19:23 UTC, mgroves commented
I added two big sections per @AV25242's feedback:  Query Results and Query Options, which largely mirror the Java documentation (except translated to the vastly superior :trollface: conventions and idioms of .NET and C#)

2020-06-10 00:11 UTC, AV25242 commented on modules/howtos/pages/n1ql-queries-with-sdk.adoc
>  Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.
Thanks Matt all changes looks good 

What kind of comment would you like to see?
All i was trying to say is explicitly mention what would be the output in each section of consistency.
you have it but its all in code. But I think thats fine lets move on :)

2020-06-10 00:11 UTC, AV25242 approved these changes

2020-06-12 09:57 UTC, RichardSmedley approved these changes

2020-06-12 09:57 UTC, merged

2020-06-12 10:38 UTC, RichardSmedley commented
Thanks @mgroves for all of the improvements - looks good.
I tweaked a couple of links post hoc btw,