Ncbc 2787 named scopes collections
couchbase/docs-sdk-dotnet pull request #195
Opened 2021-07-09 15:05 UTC by osfameron

2021-07-09 15:26 UTC, osfameron commented
Note, pending working-with-collections.html to update with info about the travel-sample app.

2021-07-13 03:11 UTC, jeffrymorris commented on modules/concept-docs/examples/Collections.csx
> +#r "nuget: CouchbaseNetClient, 3.1.7"
I did not know this existed

2021-07-13 03:11 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
>  As the Snappy compression library is not available for .NET, the server will automatically uncompress any compressed documents before sending them to the .NET client.
Interestingly enough  there is an unsupported snappy library: https://github.com/brantburnett/Snappier

Maybe we should mention it as it may become supported in the future?

2021-07-13 03:11 UTC, jeffrymorris commented on modules/concept-docs/pages/documents.adoc
>  IMPORTANT: If you are using the overloads that take `IDocument`, note that the `IDocument.Expiry` property assumes ms (milli-seconds), and is converted to seconds before being sent to the server.
This isn't true for SDK3 as IDocument is only part of the SDK2 API.

2021-07-13 03:11 UTC, jeffrymorris commented on modules/concept-docs/pages/documents.adoc
>  All other overloads take a `TimeSpan` or an `uint`, and assume an expiry in seconds
SDK3 only supports TimeSpan for expiration due to this; we no longer support integer based duration/time values.

2021-07-13 03:11 UTC, jeffrymorris commented on modules/hello-world/examples/StartUsing.cs
> +            var collection = await scope.CollectionAsync("users");
Note that there are also synchronous versions of these methods: scope.Collection("users") etc

2021-07-13 03:11 UTC, jeffrymorris commented on modules/howtos/pages/concurrent-async-apis.adoc
Maybe we should probably add a "bulk" operation example:

```
var statement = "SELECT RAW META(d).id FROM `travel-sample` as d LIMIT 1000";
--
var response = await Cluster.QueryAsync<string>(statement);
 
var batches = BatchWork(response.ToEnumerable(), 10);
foreach (var batch in batches)
{
await Task.WhenAll(batch);
}
 
...
 
static IEnumerable<IEnumerable<Task<IGetResult>>> BatchWork(IEnumerable<string> documents, int numBatches)
{
var batches = new List<List<Task<IGetResult>>>(numBatches);
for (var i = 0; i < numBatches; i++)
{
batches.Add(new List<Task<IGetResult>>());
}
 
var batchNum = 0;
foreach (var doc in documents)
{
batches[batchNum % numBatches].Add(Collection.GetAsync(doc));
batchNum++;
}
 
return batches;
}

```

2021-07-13 03:11 UTC, jeffrymorris commented on modules/howtos/pages/managing-connections.adoc
> +Currently, as of .NET SDK Version 3.0.2 there is only partial mapping of query parameters to options properties.
This isn't necessarily true anymore - most parameters are mapped now.

2021-07-13 09:42 UTC, osfameron commented on modules/hello-world/examples/StartUsing.cs
> +            var collection = await scope.CollectionAsync("users");
Ah! That would simplify the example...

I've never understood why Scope and Collection were Async, feels a bit like it caught up in  Async All The Things! excitement? But I understand that generally where `Async` methods exist, the non-Async ones are deprecated? Is this case an exception? /cc @AV25242

2021-07-13 09:43 UTC, osfameron commented on modules/concept-docs/pages/compression.adoc
>  As the Snappy compression library is not available for .NET, the server will automatically uncompress any compressed documents before sending them to the .NET client.
Happy to, but that's a product support / roadmap thing I'd have to be guided on by you / @AV25242

2021-07-13 09:46 UTC, osfameron commented on modules/concept-docs/examples/Collections.csx
> +#r "nuget: CouchbaseNetClient, 3.1.7"
Yeah! It's kinda handy cos it means you can run scripts in a directory that have different dependencies / don't all need to be compiled.

Was meaning to ask your opinion of it though, I think it's not shipped by default, but has to be installed with `dotnet tool install -g dotnet-script`.
People like Hanselman have recommended it though, so I think it's "reasonably well known"?

2021-07-13 09:47 UTC, osfameron commented on modules/howtos/pages/managing-connections.adoc
> +Currently, as of .NET SDK Version 3.0.2 there is only partial mapping of query parameters to options properties.
Sounds good - should I simply delete that line, or is there a specific instruction I can give on which parameters remain unmapped?

2021-07-14 08:35 UTC, maria-robobug approved these changes
👍  Looks good, just added some minor comments/questions. Will try to use `version-server` going forward!

2021-07-14 08:35 UTC, maria-robobug commented on modules/howtos/pages/working-with-collections.adoc
> +The 3.0 API SDKs all work with all features of Collections and Scopes.
Should this say 3.2? I guess this page will change anyway when we update with new travel-sample stuff.

2021-07-14 08:35 UTC, maria-robobug commented on modules/howtos/pages/working-with-collections.adoc
> +3.0 API versions of the Couchbase SDKs.
Same here, 3.2?

2021-07-14 08:35 UTC, maria-robobug commented on modules/ref/pages/client-settings.adoc
>  // SDK 3.0 custom k/v timeout
Should this say 3.2 now?

2021-07-14 08:35 UTC, maria-robobug commented on modules/howtos/pages/working-with-collections.adoc
> += Working with Collections
Since we have something in this page for now, should this be added to the ROOT.nav under `.Advanced Data Operations`?

2021-07-14 08:51 UTC, osfameron commented on modules/howtos/pages/working-with-collections.adoc
> +The 3.0 API SDKs all work with all features of Collections and Scopes.
or .x I guess? But yes, I think we could do with discussing the working-with-collections / travel-sample / data-model pages soon!

2021-07-14 17:47 UTC, AV25242 commented on modules/concept-docs/pages/compression.adoc
>  As the Snappy compression library is not available for .NET, the server will automatically uncompress any compressed documents before sending them to the .NET client.
@jeffrymorris / @osfameron  what I understand is that .NET SDK will need to include this SNAPPIER library and provide implementation to compress/ uncompress documents which we dont do today. I would rather keep it the way it is today before anything is made available. I agree its been asked too many times @jeffrymorris  if you think we can incorporate Snappier (from a confidence level of using this lib) then probably we can add it for our next release ? Until then we keep the doc as is is what i think

2021-07-14 18:00 UTC, AV25242 commented on modules/hello-world/examples/StartUsing.cs
> +            var collection = await scope.CollectionAsync("users");
Not an exception but a good practice to use async  function @osfameron

2021-07-14 18:59 UTC, jeffrymorris commented on modules/hello-world/examples/StartUsing.cs
> +            var collection = await scope.CollectionAsync("users");
@osfameron - my early code did a lazy lookup for scope and collection id over IO

2021-07-14 19:00 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
>  As the Snappy compression library is not available for .NET, the server will automatically uncompress any compressed documents before sending them to the .NET client.
@AV25242 - we should probably make this a planning task.

2021-07-14 19:01 UTC, jeffrymorris commented on modules/concept-docs/examples/Collections.csx
> +#r "nuget: CouchbaseNetClient, 3.1.7"
I am fine with it as long as we disclose that it needs to be installed.

2021-07-19 22:15 UTC, jeffrymorris commented on modules/concept-docs/examples/Collections.csx
> +#r "nuget: CouchbaseNetClient, 3.1.7"
Should 3.1.7 be updated to 3.2.0?

2021-07-19 22:16 UTC, jeffrymorris requested changes
Just a minor change:

`#r "nuget: CouchbaseNetClient, 3.1.7"` should probably be `#r "nuget: CouchbaseNetClient, 3.2.0"

2021-07-20 06:29 UTC, osfameron commented
> Just a minor change:
> 
> `#r "nuget: CouchbaseNetClient, 3.1.7"` should probably be `#r "nuget: CouchbaseNetClient, 3.2.0"`

OK, done!

2021-07-20 06:49 UTC, merged