NCBC-2911 update travel-sample docs and attributes
couchbase/docs-sdk-dotnet pull request #198
Opened 2021-07-19 17:14 UTC by osfameron

2021-07-19 17:17 UTC, RichardSmedley commented on modules/concept-docs/partials/attributes.adoc
> +include::project-docs:partial$attributes.adoc[]
Generally, we're deleting the unneeded attributes.adocs

2021-07-19 17:20 UTC, RichardSmedley requested changes
Afaict there are only two pages using the attributes.adoc
modules/hello-world/pages/webui-cli-access.adoc:include::partial$attributes.adoc[]
modules/howtos/pages/concurrent-document-mutations.adoc:include::partial$attributes.adoc[]
if we update them,
then all of the attributes adocs outside project-docs can be deleted.

2021-07-19 17:23 UTC, osfameron commented
> Afaict there are only two pages using the attributes.adoc
> modules/hello-world/pages/webui-cli-access.adoc:include::partial$attributes.adoc[]
> modules/howtos/pages/concurrent-document-mutations.adoc:include::partial$attributes.adoc[]
> if we update them,
> then all of the attributes adocs outside project-docs can be deleted.

Nice spot - I'll ticket removing all the additional attributes.adoc files for this sprint after Tuesday for all SDKs.

2021-07-19 17:26 UTC, osfameron commented
@RichardSmedley https://issues.couchbase.com/browse/DOC-8829

2021-07-20 14:00 UTC, RichardSmedley approved these changes
:+1:

2021-07-20 17:41 UTC, merged