Dotnet SDK 2.7.0 release notes
couchbase/docs-sdk-dotnet pull request #2
Opened 2018-10-02 22:40 UTC by jeffrymorris

2018-10-02 23:36 UTC, ingenthr requested changes
A few improvements would make this much better

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +=== New Features and Behavioural Changes
Should be en/US, right?  One too many 'u's.

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +=== Known Issues
Formatting seems off here.  We should start with new features, then cover fixes, then cover known issues, right?  I see it's not that way here already in the past though.  Can we make it consistent?  Java certainly leads with new features.  We can leave this for @RichardSmedley if need be, but it should be a quick fix.

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +* https://issues.couchbase.com/browse/NCBC-1768[NCBC-1768] -         Add automatic reties for FTS queries
Typo.  Retries, not reties.

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +* https://issues.couchbase.com/browse/NCBC-1773[NCBC-1773] -         Default span tags are missing if using another Tracer (eg Jeager)
should be e.g. I believe

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +* https://issues.couchbase.com/browse/NCBC-1661[NCBC-1661] -          SvcRestartAll-SUBDOC and  SvcRestart-SUBDOC fail on Ubuntu/Watson
Does the spacing matter here?  Why do we have a lot of space on this line after the dash, and less afterwards.

2018-10-02 23:36 UTC, ingenthr commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +* https://issues.couchbase.com/browse/NCBC-1502[NCBC-1502] -
The description of this one leaves a bit to be desired.  Can we make it a bit more clear?

2018-10-03 00:10 UTC, jeffrymorris commented on modules/ROOT/pages/relnotes-dotnet-sdk.adoc
> +=== Known Issues
I agree.

2018-10-03 01:44 UTC, closed without merging