Snappier lib
couchbase/docs-sdk-dotnet pull request #309
Opened 2023-10-17 12:38 UTC by RichardSmedley

2023-11-02 18:19 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
> +However, stable Snappy support is not yet available in the .NET platform.
This is no longer true, there is a couchbase approved Snappy lib [Snappier](https://github.com/brantburnett/Snappier) via https://github.com/couchbaselabs/Couchbase.Extensions/tree/master/src/Couchbase.Extensions.Compression.Snappier which is a plug-in into the SDK.

2023-11-02 18:49 UTC, jeffrymorris requested changes
Hi Rchard -

I think we need to work on the messaging here as we do now have the "ok" to use Snappier in prod. I do think we need to define exactly what we actually support here however.

2023-11-02 18:49 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
> +CAUTION: Community-contributed Snappy libraries are not currently supported in production -- they are linked here for you to test out performance, in the run-up to an oficially-supported solution.
Snappier has been approved for use by Couchbase as of 6/29/2023.

2023-11-02 18:49 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
> +Whilst there is no official candidate for Snappy compression in the .NET platform, with several https://google.github.io/snappy/[unsupported choices available], the community has produced a promising
I wouldn't bring this up, just direct users to the Snappier library via the [Couchbase.Extensions](https://github.com/couchbaselabs/Couchbase.Extensions) [package](https://www.nuget.org/packages/Couchbase.Extensions.Compression.Snappier/1.0.0-beta.1). (Which makes me realize we need to push a 1.0.0 GA package.

2023-11-02 18:49 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
> +See the https://github.com/brantburnett/Snappier[Snappier GitHub page] for information on installing the external Snappier library, or get it from https://www.nuget.org/packages/Snappier[NuGet].
The integration with the SDK is via the [extensions](https://github.com/couchbaselabs/Couchbase.Extensions) plugin.

2023-11-02 18:49 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
> +However, stable Snappy support is not yet available in the .NET platform.
I think we should link to the [.NET docs](https://dotnet.microsoft.com/) to make it clear was is meant here as I though you were referring to the SDK on first glance.

2023-11-02 18:49 UTC, jeffrymorris commented on modules/concept-docs/pages/compression.adoc
See my comments below.

2023-11-08 16:42 UTC, RichardSmedley commented on modules/concept-docs/pages/compression.adoc
Thanks @jeffrymorris - let me know if these changes cover it.

2023-11-27 20:52 UTC, jeffrymorris approved these changes

2023-11-27 20:52 UTC, merged