NCBC-3678: Docs samples for SDK 3.5 features
couchbase/docs-sdk-dotnet pull request #321
Opened 2024-03-04 17:10 UTC by RiPont

* Scoped search examples
* Vector search examples
* refactored from inline examples to CSPROJ example that compiles.

RangeScan and GetAny/AllReplicas still TODO

2024-03-04 17:51 UTC, SecureCake commented on modules/howtos/examples/Couchbase.Examples.SearchV2/SearchV2Examples/Program.cs
> +    EnableDnsSrvResolution = false,
NIT: tiny extra "," here

2024-03-05 00:22 UTC, jeffrymorris requested changes
Hi Richard -

I think you are missing KV Range Scan  and Read from Replica docs. via https://issues.couchbase.com/browse/CBD-5804

2024-03-05 02:06 UTC, RiPont commented on modules/howtos/examples/Couchbase.Examples.SearchV2/SearchV2Examples/Program.cs
> +    EnableDnsSrvResolution = false,
That's idiomatic modern C#.  :)  Compiles just fine.

2024-03-05 15:44 UTC, RichardSmedley approved these changes
Thanks @RiPont 
LGTM

2024-03-05 15:44 UTC, merged