Doc 5743 tracing
couchbase/docs-sdk-dotnet pull request #61
Opened 2019-10-01 18:19 UTC by RichardSmedley

2019-10-02 19:19 UTC, MikeGoldsmith requested changes

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +When false a Noop or similar tracing implementation should be used instead.
"When false a Noop tracing implementation is used instead."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The maximum number of items to log per service.
This is the number of sampled traces to log - maybe something like "The maximum number of sampled traces to log per service."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The N1QL query operation threshold.
Standardised name is just 'query' for n1ql so I'd go with "The query operation threshold."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The FTS query operation threshold.
"The search operation threshold."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The Analytics query operation threshold.
Should _Analytics_ capitalised?

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The interval used to flush orphaned response information to the log.
I like the ThresholdLogger description style better, something like:
"The interval between executions that process orphaned responses to the log."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +| The number of sample orphaned responses whose to log additional information for per execution.
Same as ThresholdLogger description:
"The maximum number of sampled orphaned responses to log."

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/client-settings.adoc
> +Applying these as client-level settings with App.Config (or Web.Config) can be done as follows:
Don't need capitalisation, should just be web.config / web.config.

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/tracing-from-the-sdk.adoc
> +* *last_dispatch_us:* The time taken for the last dispatch to the server: around 1 millisecond.
As an operation may be retried, it's important to indicate that *last*_ properties are for the most recent socket hostname & port used to send the operation.

2019-10-02 19:19 UTC, MikeGoldsmith commented on modules/ROOT/pages/tracing-from-the-sdk.adoc
> +// TODO look into the Java bug whereby one of them is not aggregated
Should remove TODO for java follow up 😄

2019-10-03 10:28 UTC, MikeGoldsmith approved these changes

2019-10-03 10:28 UTC, RichardSmedley commented on modules/ROOT/pages/client-settings.adoc
> +| The Analytics query operation threshold.
Yes, as with Query and Search, here referring directly to one of our services.

2019-10-03 10:29 UTC, RichardSmedley commented on modules/ROOT/pages/tracing-from-the-sdk.adoc
> +* *last_dispatch_us:* The time taken for the last dispatch to the server: around 1 millisecond.
Thanks - added this as note to `last_local_address`

2019-10-03 10:31 UTC, merged